### ISSUE TITLE
Application cannot detect custom-named game folder

### ISSUE THREAD

**Issue by Scarlaid** [ShadowyLycan990/ZenlessZoneZero-render-fix#2]
I have a habit of not naming folders correctly and this applies to using Starward as an alternative Mihoyo-related games launcher
~~It seems like the program only detect the folder with the name `ZenlessZoneZero` and nothing else~~
Mistaken, it reads registry but I don't think Starward does this

Maybe adding a way to add directory manually?
![image](https://github.com/user-attachments/assets/d13b59a4-72d0-477b-a040-c981b300f8dc)

**Comment by ShadowyLycan990** [comment]
Thanks for the suggestion, I'll add it later when I have a free time today.

**Comment by ShadowyLycan990** [comment]
@Scarlaid, now the tool is updated with the method that you asked for.
Thanks for the suggestion!

**Comment by Scarlaid** [comment]
worth the wait, thank you you absolute legend :)
